EXPERIMENT_LABEL = "vgg1"
TRAIN_PATH = 'train'
TEST_PATH = 'test'

BASE_IMG_DIR = 'data/'
RANDOM_SEED = 42

PRETRAINED = False
PRETRAINED_MODEL_PATH = 'without_pretrained_vgg16'

LEARNING_RATE = 3.98E-04

BATCH_SIZE = 32
IMAGE_DIMS = 224

EPOCHS = 2

BASE_MODEL = 'vgg16'
