EXPERIMENT_LABEL = "nasnet_v1"
TRAIN_PATH = 'train'
TEST_PATH = 'test'

BASE_IMG_DIR = 'data/'
GENERATOR_RANDOM_SEED = 42
PRETRAINED = False

BATCH_SIZE = 32
IMAGE_DIMS = 224

EPOCHS = 2

BASE_MODEL = 'vgg16'
METRIC = 'accuracy'
